### ISSUE TITLE
[Bug]: Allthemodium leaves don't have hitbox

### ISSUE THREAD

**Issue by YocyCraft** [AllTheMods/AllTheModium#110]
### Possible Fixes

Yes

### Modpack Version

ATM10 - 1.7

### What happened?

Players can walk through ancient, soul and demonic leaves.
![2024-10-25_18 13 58](https://github.com/user-attachments/assets/6f93ebea-ccd3-407e-9f60-af2a98fb0d1f)

**Comment by thevortex** [comment]
this is an intentional choice for the leaves
