### ISSUE TITLE
Crash event on World Creation

### ISSUE THREAD

**Issue by Zelioth** [AllTheMods/AllTheModium#118]
Minecraft 1.21.1
NeoForge 21.1.73
AllTheModium 2.7.2

Client Crashes on world creation screen. Will provide logs. 
[latest.log](https://github.com/user-attachments/files/17549876/latest.log)
[debug.log](https://github.com/user-attachments/files/17549877/debug.log)
[crash-2024-10-28_18.35.50-client.txt](https://github.com/user-attachments/files/17549878/crash-2024-10-28_18.35.50-client.txt)

**Comment by thevortex** [comment]
i just pushed 2.7.3 to curseforge, can you give it a try and let me know the results

**Comment by Zelioth** [comment]
I can. Give me a few minutes to test and I will let you know . Thank you so much

**Comment by Zelioth** [comment]
YES, It appears that 2.7.3 version fixes the crash when pressing the "Single Player" button before preparing world creation. Thank you :D

**Comment by thevortex** [comment]
awesome!
