### ISSUE TITLE
[Bug]: ATM alloy paxel does not have a high enough mining level to mine allthemodium ores

### ISSUE THREAD

**Issue by dexmEl** [AllTheMods/AllTheModium#119]
### Possible Fixes

Yes

### Modpack Version

ATM10 - 1.11

### What happened?

Mentioned in title.

**Comment by thevortex** [comment]
do you happen to have miners fervor on the pick/paxel ? tools with that enchant are unable to break the ATM ores. i tested with an unenchanted paxel and am able to break all 3 of the ores
