### ISSUE TITLE
[Bug]: allthemodium enchanting

### ISSUE THREAD

**Issue by EnotScript** [AllTheMods/AllTheModium#120]
### Possible Fixes

Yes

### Modpack Version

ATM10 - 0.41

### What happened?

Items from Allthemodium + addon not enchantable after update.

**Comment by Satherov** [comment]
That's a known issue and will be fixed soon. Until then, you have to enchant your gear before turning it into allthemodium gear

**Comment by StyLexR6** [comment]
Still an issue on 0.46

**Comment by Satherov** [comment]
This issue was fixed in the latest version of AllTheModium. You can either update the mod manually or wait for 0.47
