### ISSUE TITLE
[Bug]: Miners Favor not working with vibranium ore in the other

### ISSUE THREAD

**Issue by adrian-goe** [AllTheMods/AllTheModium#127]
### Possible Fixes

Yes

### Modpack Version

ATM10 - 1.0

### What happened?

Miners Favor (I had 5) on an Allthemodium Pickaxe does not allow to mine Vibranium ore in the other.

The hint, that this is a bug was coming in discord from and developer

**Comment by jeremiahwinsley** [comment]
This is a known issue, but there is no way to fix this without disabling the mining protection on ores.
