### ISSUE TITLE
AllTheModium shows error when Ars Nouveau isn't install

### ISSUE THREAD

**Issue by Odesy-A-Journey** [AllTheMods/AllTheModium#135]
![image](https://github.com/user-attachments/assets/9c0fc19f-8545-4f10-9918-ca9890b5f7bd)

**Comment by thevortex** [comment]
sorry about that, dependencies weren't marked correctly for that, will get a fixed build up today

**Comment by thevortex** [comment]
2.8.4 just uploaded to curseforge https://legacy.curseforge.com/minecraft/mc-mods/allthemodium/files/6017303 
issue resolved!
