### ISSUE TITLE
Incompatibility to some nether biome mod

### ISSUE THREAD

**Issue by sutepu-chan** [AllTheMods/AllTheModium#15]
For 1.16.5, the mod is incompatible with other nether generation mod
Biome from "the other" dimension will generate in the nether dimension, if the mod is put together with other mods that add biomes to the nether, e.g., infernal expansion, betternether forge, etc
But this mod is compatible with other nether mod such as deeper nether biomes, nourished nether.

**Comment by sutepu-chan** [comment]
![unknown-1](https://user-images.githubusercontent.com/101050569/160616966-2d5f2022-c453-4a20-a2c4-ad4cf4696fda.png)
Here is the mod i am testing with. The issue mentioned is solved by just removing infernal expansion

**Comment by jeremiahwinsley** [comment]
This looks like an issue with Infernal Expansion - they add all biomes in the nether category to the Nether, whether they should be spawning there or not.

https://github.com/infernalexp/Infernal-Expansion/blob/8d518702601726506b01dd7624c28cd1725f6736/src/main/java/org/infernalstudios/infernalexp/world/dimension/ModNetherBiomeCollector.java#L39
