### ISSUE TITLE
Crash when trying to enter/make a world.

### ISSUE THREAD

**Issue by TDCMC** [AllTheMods/AllTheModium#16]
Hello, I'm using allthemodium in my own custom collection of mods and I have encountered a problem. The game crashes everytime I try to enter an existing world or create a new world.

AllTheModium version: allthemodium-1.7.0rc6-1.18.1-39.0.10
Minecraft: version: 1.18.1
Crash log: [crash-2022-03-24_17.31.21-client.txt](https://github.com/AllTheMods/AllTheModium/files/8403972/crash-2022-03-24_17.31.21-client.txt)

Just looking at the crash log, I can see an obvious problem. That is, a class is used from AllTheOres without checking if the mod is installed or not.

**Comment by thevortex** [comment]
will have a fix for this later today, thanks!

**Comment by Realever** [comment]
hi,
i have the same error when i click in the main menu on single player but on 1.18.2.I use your mod for my private modpack.Here is the [crash report](https://pastebin.com/Hdj39fNH)

**Comment by thevortex** [comment]
https://www.curseforge.com/minecraft/mc-mods/allthemodium/files/3826741 (awaiting approval at time of this post) update 1.8.1 resolves the dependency on alltheores. you will need to datapack in ore features for the mining dim/other if you use those dimensions
