### ISSUE TITLE
Crash when attempting to use Allthemodium without Mekanism

### ISSUE THREAD

**Issue by taj1994** [AllTheMods/AllTheModium#19]
Allthemodium version 1.7.6-1.18.2-40.1.0

[crash-2022-05-03_02.48.36-fml.txt](https://github.com/AllTheMods/AllTheModium/files/8609417/crash-2022-05-03_02.48.36-fml.txt)

**Comment by thevortex** [comment]
most recent update( 1.7.7 ) fixes this issue, it's currently waiting on curseforge approval
