### ISSUE TITLE
[1.18.2] Missing soul lava alloying recipe

### ISSUE THREAD

**Issue by Lordfirespeed** [AllTheMods/AllTheModium#22]
Mod version 1.8.1
Forge 40.1.31, running All The Mods 7. Recipe is missing when I look in the jarfile -> data -> allthemodium -> recipes -> alloys.

**Comment by thevortex** [comment]
which alloy are you trying to make? you cannot craft soul lava in 1.18

**Comment by Lordfirespeed** [comment]
Previous versions featured a recipe for soul lava. I was wondering if it was a mistake that the recipe had been removed ?

**Comment by thevortex** [comment]
nope, this was intentional, soul lava can be found in "the other" dimension in volcanos(ancient basalt deltas biomes) and piglin villages sometimes contain small amounts

**Comment by Lordfirespeed** [comment]
Previous versions featured a recipe for soul lava. I was wondering if it
was a mistake that the recipe had been removed ?

**Comment by thevortex** [comment]
please re-read my previous comment
