### ISSUE TITLE
It just doesn't work (1.18.2)

### ISSUE THREAD

**Issue by CapivaraTupiniquim** [AllTheMods/AllTheModium#26]
If I load a brand new instance, with only Forge and Mod, the game doesn't open.

![image](https://user-images.githubusercontent.com/67530921/184556924-d5723171-e7aa-499d-9ef3-42dd946a5a26.png)

**Comment by thevortex** [comment]
ahh yeah it needs geckolib now for handling the piglich animations, apologies i didn't mark the file on curseforge

**Comment by CapivaraTupiniquim** [comment]
Sorry for that inssue, i don't think that, thanks! (Sorry for the bad english)
