### ISSUE TITLE
[Crash]: error in selected data packages

### ISSUE THREAD

**Issue by BryTadeira** [AllTheMods/AllTheModium#33]
### Possible Fixes

Yes

### Modpack Version

1.8.28

### What happened?

every time I create a new world with all the modium it loads normally. But when I save, exit and try to enter again it does not enter, and says: error in selected data packages prevented the world from loading. I already tested all the modium and it entered normally. addendum, I only use the separate all the modium.

I didn't put a line of code because it doesn't appear

### Crash Log

https://gist.github.com/BryTadeira/672168492af48115698c44b5c8a5cc20

**Comment by jeremiahwinsley** [comment]
If you don't have a crash log, then post your regular latest.log. Not sure what you mean by "separate all the modium". Did you add any mods to the pack, or is it the default pack?

**Comment by BryTadeira** [comment]
the only thing i have is this picture:
https://user-images.githubusercontent.com/112587244/202817637-4cb92d5b-bd94-473c-8520-f4bb52f09312.png

the place I downloaded the mod was in cursed forge in this version 2.1.2
https://user-images.githubusercontent.com/112587244/202818066-27425490-a886-47f6-bbca-815969deb472.png

**Comment by jeremiahwinsley** [comment]
I have transferred this to the AllTheModium repo, since you are not playing ATM-6. If you are using the vanilla launcher, you should be able to go to the `mods` folder where you added the mod, go up one level, and then you should have a `logs` folder containing `latest.log`. Post that latest.log.

**Comment by BryTadeira** [comment]
there are these two the "latest" was from now on and the 2022-11-18 four minutes before the "latest"

https://github.com/AllTheMods/AllTheModium/files/10045489/2022-11-18-1.log
https://github.com/AllTheMods/AllTheModium/files/10045490/latest.log

**Comment by jeremiahwinsley** [comment]
Looks like you do not have AllTheOres, which is required by AllTheModium - https://www.curseforge.com/minecraft/mc-mods/ato/files/4046926

**Comment by BryTadeira** [comment]
thank you very much friend, 100% solved my problem. I didn't know I needed this mod because it doesn't speak in cursed forge. Thank you very much for your attention and affection
<img width="462" alt="lklklk" src="https://user-images.githubusercontent.com/112587244/202825587-cf8f6835-2903-48b3-8a97-c5313e688bd9.png">
