### ISSUE TITLE
Armors missing, and allthemodium weak

### ISSUE THREAD

**Issue by BryTadeira** [AllTheMods/AllTheModium#36]
I'm playing Allthemodium with mods, I don't use allthemods modpack, and I noticed that unobtainium and vibranium armor are missing. And also the allthemodium armor is equivalent to a diamond armor, follow the images below.

<img width="960" alt="Captura de tela 2022-12-02 223557" src="https://user-images.githubusercontent.com/112587244/205416758-b114879c-b8e3-4baf-8251-55bbf91c2edf.png">

<img width="960" alt="Captura de tela 2022-12-02 223733" src="https://user-images.githubusercontent.com/112587244/205416764-29be5bed-ac40-44dd-8e2f-95e95bb1a812.png">

<img width="960" alt="Captura de tela 2022-12-02 224028" src="https://user-images.githubusercontent.com/112587244/205416775-60eaab47-92c3-421e-9484-feabc61b9a66.png">

[latest.log](https://github.com/AllTheMods/AllTheModium/files/10145358/latest.log)

please help me, thank you in advance!

**Comment by Mitchell5200** [comment]
Allthemodium armor was rebalanced in 1.19, and the other two have been removed, i'm not sure if they're returning yet, but no not a bug.

**Comment by BryTadeira** [comment]
> Allthemodium armor was rebalanced in 1.19, and the other two have been removed, i'm not sure if they're returning yet, but no not a bug.

but is there a reason for that?  because in version 1.18 it was 200 armor more or less, and now it's only 9, isn't that a very exaggerated change for what the mod proposes?  and why take away the other two armors?  Wasn't that a very exaggerated change?

**Comment by James103** [comment]
> Allthemodium armor was rebalanced in 1.19, and the other two have been removed, i'm not sure if they're returning yet, but no not a bug.

If you migrate to All the Mods 9 for Minecraft 1.20.1, you should see Vibranium and Unobtainium armor and tools.
