### ISSUE TITLE
1.19.2 prevent BOP and OBG log stripping 

### ISSUE THREAD

**Issue by Joshernoob** [AllTheMods/AllTheModium#38]
Version: allthemodium-2.1.3-1.19.2-43.1.1 
Forge: 43.2.0
BOP Version: BiomesOPlenty-1.19.2-17.1.1.162
OBG Version: Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13

To remake:
Added mods to a pack
try to right click any BOP or OBG logs with an axe
the logs will not strip as intended

**Comment by Jack-McKalling** [comment]
These mods are also required:
geckolib-forge-1.19-3.1.39
TerraBlender-forge-1.19.2-2.0.1.130

It turns out that with these installed, I was able to run the game in "safe mode" without any datapacks, after I got this error: #33
But that way it never complained about not having AllTheOres installed.

**Comment by Joshernoob** [comment]
> 

https://pastebin.com/vmvZdKLq
