### ISSUE TITLE
Crash while trying to create a new world (1.16.5)

### ISSUE THREAD

**Issue by TDCMC** [AllTheMods/AllTheModium#39]
I'm NOT playing the All The Mods 6 pack and whenever I press "Create a new world", the games crashes.
Forge version: 36.2.39
Allthemodium version: allthemodium-1.5.18-1.16.5-36.1.23

Crash Report: [crash-report.txt](https://github.com/AllTheMods/AllTheModium/files/10333161/crash-report.txt)
Log: [latest-log.log](https://github.com/AllTheMods/AllTheModium/files/10333166/latest-log.log)

**Comment by TDCMC** [comment]
If it helps, I something related to an object or variable or whatever called HIPPOCAMPUS being not defined in the logs.

**Comment by jeremiahwinsley** [comment]
Currently AllTheModium 1.16 only supports Ice and Fire version 2.1.9, you have 2.1.11.

**Comment by TDCMC** [comment]
> Currently AllTheModium 1.16 only supports Ice and Fire version 2.1.9, you have 2.1.11.

My bad on that one, but the issue still persists.
[latest-log.log](https://github.com/AllTheMods/AllTheModium/files/10336043/latest-log.log)
[crash-report.txt](https://github.com/AllTheMods/AllTheModium/files/10336056/crash-report.txt)

**Comment by jeremiahwinsley** [comment]
That latest crash report still has iceandfire-2.1.11-1.16.5.jar

**Comment by TDCMC** [comment]
Forgot to remove the new version. Thank you very much! Just out of curiosity, do you plan on updating the 1.16.5 anymore?
