### ISSUE TITLE
No generating Ores in ATM Mining Dim

### ISSUE THREAD

**Issue by IXOlex** [AllTheMods/AllTheModium#40]
Hey, there is a prob with the mod, when I create the teleport pad and going to the mining dim, there are no ores, only cobble /grass/ deep slate and bedrock, pretty embarrassing with a Mining dim xD 
But in the Other there are all ores, pretty fine, so I don't know what is it because I try a lot of supply mods to see the error and none of them generating ores

Thanks

**Comment by TheBedrockMaster** [comment]
Need more information, like what version of Minecraft and the mod was in use?
