### ISSUE TITLE
Game crashes when I want to open a World

### ISSUE THREAD

**Issue by Brisingr23** [AllTheMods/AllTheModium#45]
Hey there,
whenever I want to load or create a new World my Game keeps crashing with Exit Code: -1
I think there´s some kind of complication from allthemodium, because if I remove the mod it just runs fine. 
Is there any way to solve this issue without removing allthemodium or any other mods I´m using?
Thanks

**Comment by Mitchell5200** [comment]
crashlogs and Latest.logs would help, as would mod versions, forge versions, MC version, 
https://mclo.gs/ for logs

**Comment by TheSusporiumYTalt** [comment]
was this solved? im having the same issue

**Comment by jeremiahwinsley** [comment]
The most common cause of crashes is that you are missing some dependency, AllTheModium requires GeckoLib and AllTheOres.  If you don't post your logs, we have no way of knowing whether that's your issue or not.
