### ISSUE TITLE
Game Crashes when trying to click create new world or trying to join a pre-existing one.

### ISSUE THREAD

**Issue by ForzaWasTaken** [AllTheMods/AllTheModium#46]
It works fine without alllthemodium but is there any way to make it work with it?

crash report: https://bytebin.lucko.me/3L3OY5a5Fa

**Comment by jeremiahwinsley** [comment]
You have an incompatible version of ice and fire - allthemodium 1.16 is currently only compatible with the version we're using in ATM6, which is 2.1.9.
