### ISSUE TITLE
Recipe incompatibility

### ISSUE THREAD

**Issue by Nintadso** [AllTheMods/AllTheModium#49]
After a recent Ice and Fire update on 1.16.5, the string for Dragon forge recipes have changed, which makes the alloy recipes of ATM broken. I've tried changing the recipe string in the json files for the recipes, but it didn't seem to work... I know you changed the mod that allows alloy recipes in more recent versions, but it'd be nice if this could be fixed for 1.16.

**Comment by thevortex** [comment]
allthemodium only supports up until the version 2.1.9 of ice and fire unfortunately
