### ISSUE TITLE
Minecraft crashes when trying to create new world or joining an existing one

### ISSUE THREAD

**Issue by MiaNbrdr** [AllTheMods/AllTheModium#57]
Trying to add allthemodium to my modpack, Version 1.20.1, Minecraft itself launches fine, But crashes when trying to create or join a world, When trying to join an existing world, It gives me this error: "Errors in currently selected Data Packs prevented the world from loading. You can either try to load it with only the Vanilla Data Pack ("Safe Mode"), or go back to the title screen and fix it manually." Clicking on Safe Mode freezes the game for about 10 seconds, Then doesn't do anything else, I have no idea how I'm supposed to fix this "Manually". Older versions of Allthemodium have the same issue.

**Comment by SeigneurGhost** [comment]
Good evening, I have the same problem, I wanted to open the map of my server 0.0.65 to retrieve schematics solo but it doesn't work and I have the same error message.

**Comment by MiaNbrdr** [comment]
> Good evening, I have the same problem, I wanted to open the map of my server 0.0.65 to retrieve schematics solo but it doesn't work and I have the same error message.

Ah that sucks! I hope my post gives you a solution aswell :)

**Comment by jeremiahwinsley** [comment]
This is most likely a missing dependency, do you have Geckolib and AllTheOres installed? If so, please post your latest.log

**Comment by MiaNbrdr** [comment]
> This is most likely a missing dependency, do you have Geckolib and AllTheOres installed? If so, please post your latest.log

I had Geckolib, But not AllTheOres, I'll try to launch it again with AllTheOres later and will let you know what happens

**Comment by MiaNbrdr** [comment]
Can confirm, Allthemodium needs Geckolib AND AllTheOres to be able to launch the game and open your worlds, Thanks for the help fellow Minecrafters

**Comment by d1vinity123** [comment]
do you know how do i acquire the alltheores mod by any chance? im facing the same problem yet i cant find the mod it self.

**Comment by jeremiahwinsley** [comment]
> do you know how do i acquire the alltheores mod by any chance? im facing the same problem yet i cant find the mod it self.

Same way you get AllTheModium, from Curseforge
