### ISSUE TITLE
Game crashes without All the Ores/All the Ores is not listed as a dependency

### ISSUE THREAD

**Issue by iron431** [AllTheMods/AllTheModium#65]
Whether intentional or not, Allthemodium has a hard requirement for All the Ores. 

However, it is not listed as a dependency in CurseForge nor the mods.toml, which causes users confusion because they are allowed to launch the game, but then the game crashes on worldgen unexpectedly.

Crashlogs can be found here:
https://github.com/iron431/all-the-wizard-armor/issues/2
https://github.com/iron431/all-the-wizard-armor/issues/1

**Comment by thevortex** [comment]
will send a fix for this tonight, i do have it on curseforge showing as a dependency, also geckolib, but my b about the mods.toml

**Comment by iron431** [comment]
it may not be listed as required then, as the curseforge launcher does not automatically install All the Ores like it usually installs all the required dependencies.

**Comment by thevortex** [comment]
https://www.curseforge.com/minecraft/mc-mods/allthemodium/files/4838986 fixes this (v2.4.3 )
