### ISSUE TITLE
iceandfire incompatibility

### ISSUE THREAD

**Issue by pibblepower** [AllTheMods/AllTheModium#67]
Hey, I just added the new iceandfire 1.19.2 beta alongside this mod. the game then stops and says it only supports ice and fire 2.1 or above (I'm using 2.1.13-beta-3). I feel like this isn't suppose to happen, so can this be fixed?

(Here's the log file line: [11:58:11] [Render thread/FATAL] [ne.mi.fm.ModLoader/CORE]: Error during pre-loading phase
net.minecraftforge.fml.ModLoadingException: Mod §eallthemodium§r only supports §3iceandfire§r §o2.1 or above§r
§7Currently, §3iceandfire§r§7 is §o1.19.2-2.1.13+build.beta-3)

**Comment by thevortex** [comment]
fix for this coming, was an unused artifact in the code left over from atm6
