### ISSUE TITLE
Trying the gradle build the mod but don't know where the jar is

### ISSUE THREAD

**Issue by VenerableTimeWanderer** [AllTheMods/AllTheModium#70]
Can someone please tell me where it builds the mod, looked everywhere and I don't even know if it is working.

**Comment by thevortex** [comment]
check in the /build/libs folder :)

**Comment by VenerableTimeWanderer** [comment]
Yeah that wasn't there before. Been on this problem for like a week now and I just figured out what I was doing wrong which I never was using the gradle extension at all. So nothing was working. Thanks for the help :)
