### ISSUE TITLE
Tools can't be enchanted on enchantment table

### ISSUE THREAD

**Issue by YocyCraft** [AllTheMods/AllTheModium#94]
![2024-08-31_15 50 10](https://github.com/user-attachments/assets/9ae24448-982e-4c74-bb15-7537f324ebe6)
![2024-08-31_15 50 15](https://github.com/user-attachments/assets/50fb507e-1a38-4bcc-970a-3b38c385b5a3)

**Comment by Satherov** [comment]
Known Issue with ATM gear at the moment. It's getting fixed soon, but until then, the only way to get enchantments on them is having them enchanted before you upgrade it to AllTheModium
